### ISSUE TITLE
Sesuaikan nama dengan aplikasi lama

### ISSUE THREAD

**Issue by pascalalfadian** [cikalmaulana/WSDC2017BaliV2#1]
Hi @cikalmaulana 

Bisa tolong package name dan app name nya disamakan dengan aplikasi lama?

<img width="1092" alt="Screenshot 2022-04-29 at 11 22 13" src="https://user-images.githubusercontent.com/5976057/165884984-6206d241-5358-4505-8c1a-6d2ad414db1e.png">

Trims.

**Comment by cikalmaulana** [comment]
Halo pak, apakah benar kalau package name nya : "org.wsdc2017indonesia.app" dan app name nya : "WSDC 2017"? Kalau iya, sudah saya ganti ya pak.

**Comment by pascalalfadian** [comment]
Trims. Kalau package name sih kayaknya benar. Tapi app name nya itu, kalau kamu lihat di screenshot saya `App`. Kalau di commit kamu 58941104e6f0b754c580f8b1b26deda6ad21c596 itu nama sebelumnya `WSDC 2017 Bali V2`. Saya nggak tahu ini dipakainya di mana, tapi bisa kamu tolong cari dulu di source code nya itu apakah `App` nya itu bisa diganti juga?

**Comment by cikalmaulana** [comment]
Saya masih belum ketemu pak dimana, tapi saya sudah coba samakan dengan yg lama untuk setiap name nya.

**Comment by pascalalfadian** [comment]
OK trims. Besok saya coba lagi ya.

**Comment by pascalalfadian** [comment]
Sepertinya memang tidak bisa diubah, bawaan dari Capacitor.
